//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roomBooking.SOAPEmailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicecall.mcds5510.com", ConfigurationName="SOAPEmailService.Service_Call")]
    public interface Service_Call {
        
        // CODEGEN: Generating message contract since element name eMailid from namespace http://servicecall.mcds5510.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        roomBooking.SOAPEmailService.sendMailResponse sendMail(roomBooking.SOAPEmailService.sendMailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<roomBooking.SOAPEmailService.sendMailResponse> sendMailAsync(roomBooking.SOAPEmailService.sendMailRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://servicecall.mcds5510.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        roomBooking.SOAPEmailService.checkLoginResponse checkLogin(roomBooking.SOAPEmailService.checkLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<roomBooking.SOAPEmailService.checkLoginResponse> checkLoginAsync(roomBooking.SOAPEmailService.checkLoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMail", Namespace="http://servicecall.mcds5510.com", Order=0)]
        public roomBooking.SOAPEmailService.sendMailRequestBody Body;
        
        public sendMailRequest() {
        }
        
        public sendMailRequest(roomBooking.SOAPEmailService.sendMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicecall.mcds5510.com")]
    public partial class sendMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string eMailid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string message;
        
        public sendMailRequestBody() {
        }
        
        public sendMailRequestBody(string eMailid, string message) {
            this.eMailid = eMailid;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMailResponse", Namespace="http://servicecall.mcds5510.com", Order=0)]
        public roomBooking.SOAPEmailService.sendMailResponseBody Body;
        
        public sendMailResponse() {
        }
        
        public sendMailResponse(roomBooking.SOAPEmailService.sendMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicecall.mcds5510.com")]
    public partial class sendMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendMailReturn;
        
        public sendMailResponseBody() {
        }
        
        public sendMailResponseBody(string sendMailReturn) {
            this.sendMailReturn = sendMailReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkLogin", Namespace="http://servicecall.mcds5510.com", Order=0)]
        public roomBooking.SOAPEmailService.checkLoginRequestBody Body;
        
        public checkLoginRequest() {
        }
        
        public checkLoginRequest(roomBooking.SOAPEmailService.checkLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicecall.mcds5510.com")]
    public partial class checkLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public checkLoginRequestBody() {
        }
        
        public checkLoginRequestBody(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkLoginResponse", Namespace="http://servicecall.mcds5510.com", Order=0)]
        public roomBooking.SOAPEmailService.checkLoginResponseBody Body;
        
        public checkLoginResponse() {
        }
        
        public checkLoginResponse(roomBooking.SOAPEmailService.checkLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicecall.mcds5510.com")]
    public partial class checkLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool checkLoginReturn;
        
        public checkLoginResponseBody() {
        }
        
        public checkLoginResponseBody(bool checkLoginReturn) {
            this.checkLoginReturn = checkLoginReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service_CallChannel : roomBooking.SOAPEmailService.Service_Call, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_CallClient : System.ServiceModel.ClientBase<roomBooking.SOAPEmailService.Service_Call>, roomBooking.SOAPEmailService.Service_Call {
        
        public Service_CallClient() {
        }
        
        public Service_CallClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_CallClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_CallClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_CallClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        roomBooking.SOAPEmailService.sendMailResponse roomBooking.SOAPEmailService.Service_Call.sendMail(roomBooking.SOAPEmailService.sendMailRequest request) {
            return base.Channel.sendMail(request);
        }
        
        public string sendMail(string eMailid, string message) {
            roomBooking.SOAPEmailService.sendMailRequest inValue = new roomBooking.SOAPEmailService.sendMailRequest();
            inValue.Body = new roomBooking.SOAPEmailService.sendMailRequestBody();
            inValue.Body.eMailid = eMailid;
            inValue.Body.message = message;
            roomBooking.SOAPEmailService.sendMailResponse retVal = ((roomBooking.SOAPEmailService.Service_Call)(this)).sendMail(inValue);
            return retVal.Body.sendMailReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<roomBooking.SOAPEmailService.sendMailResponse> roomBooking.SOAPEmailService.Service_Call.sendMailAsync(roomBooking.SOAPEmailService.sendMailRequest request) {
            return base.Channel.sendMailAsync(request);
        }
        
        public System.Threading.Tasks.Task<roomBooking.SOAPEmailService.sendMailResponse> sendMailAsync(string eMailid, string message) {
            roomBooking.SOAPEmailService.sendMailRequest inValue = new roomBooking.SOAPEmailService.sendMailRequest();
            inValue.Body = new roomBooking.SOAPEmailService.sendMailRequestBody();
            inValue.Body.eMailid = eMailid;
            inValue.Body.message = message;
            return ((roomBooking.SOAPEmailService.Service_Call)(this)).sendMailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        roomBooking.SOAPEmailService.checkLoginResponse roomBooking.SOAPEmailService.Service_Call.checkLogin(roomBooking.SOAPEmailService.checkLoginRequest request) {
            return base.Channel.checkLogin(request);
        }
        
        public bool checkLogin(string userName, string password) {
            roomBooking.SOAPEmailService.checkLoginRequest inValue = new roomBooking.SOAPEmailService.checkLoginRequest();
            inValue.Body = new roomBooking.SOAPEmailService.checkLoginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            roomBooking.SOAPEmailService.checkLoginResponse retVal = ((roomBooking.SOAPEmailService.Service_Call)(this)).checkLogin(inValue);
            return retVal.Body.checkLoginReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<roomBooking.SOAPEmailService.checkLoginResponse> roomBooking.SOAPEmailService.Service_Call.checkLoginAsync(roomBooking.SOAPEmailService.checkLoginRequest request) {
            return base.Channel.checkLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<roomBooking.SOAPEmailService.checkLoginResponse> checkLoginAsync(string userName, string password) {
            roomBooking.SOAPEmailService.checkLoginRequest inValue = new roomBooking.SOAPEmailService.checkLoginRequest();
            inValue.Body = new roomBooking.SOAPEmailService.checkLoginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((roomBooking.SOAPEmailService.Service_Call)(this)).checkLoginAsync(inValue);
        }
    }
}
